// <auto-generated />
using System;
using Fiap.Api.Donation2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240124004602_AddProdutos")]
    partial class AddProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation2.Models.CategoriaModel", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8180),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8181),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 1",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8194),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8195),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 2",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8198),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8199),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 3",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8202),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8203),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 4",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8272),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8273),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 5",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8276),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8277),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8279),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8280),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8282),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8283),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8285),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8286),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8288),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8289),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8291),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8291),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8294),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8294),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8296),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8297),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8299),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8300),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8302),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8303),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8305),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8305),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8307),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8308),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8310),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8311),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8314),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8314),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8316),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8317),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8319),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8320),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8322),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8323),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8325),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8326),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8328),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8329),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8331),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8332),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8334),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8335),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8337),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8338),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8340),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8340),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8343),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8343),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8346),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8346),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2024, 1, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8348),
                            DataExpiracao = new DateTime(2025, 9, 23, 21, 46, 2, 102, DateTimeKind.Local).AddTicks(8349),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Fiap.Api.Donation2.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation2.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation2.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
